jdbc.user=root
jdbc.password=LJQ20110627
jdbc.driverClass=com.mysql.cj.jdbc.Driver
jdbc.jdbcUrl=jdbc:mysql://localhost:3306/wms_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
jdbc.testConnectionOnCheckout=true
jdbc.initialPoolSize=3
jdbc.minPoolSize=3
jdbc.maxPoolSize=15
jdbc.acquireIncrement=3
jdbc.maxIdleTime=600
jdbc.idleConnectionTestPeriod=60
jdbc.acquireRetryAttempts=30
jdbc.acquireRetryDelay=1000
jdbc.testConnectionOnCheckin=true
jdbc.automaticTestTable=c3p0_test
jdbc.checkoutTimeout=30000
jdbc.preferredTestQuery=SELECT 1
