jdbc.user=root
jdbc.password=LJQ20110627
jdbc.driverClass=com.mysql.cj.jdbc.Driver
jdbc.jdbcUrl=jdbc:mysql://localhost:3306/wms_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
jdbc.testConnectionOnCheckout=true
