jdbc.user=root
jdbc.password=LJQ20110627
jdbc.driverClass=com.mysql.cj.jdbc.Driver
jdbc.jdbcUrl=jdbc:mysql://localhost:3306/wms_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
jdbc.testConnectionOnCheckout=true
jdbc.maxPoolSize=20
jdbc.minPoolSize=5
jdbc.initialPoolSize=10
jdbc.maxIdleTime=300
jdbc.acquireIncrement=5
jdbc.maxStatements=0
jdbc.idleConnectionTestPeriod=60
jdbc.acquireRetryAttempts=30
jdbc.breakAfterAcquireFailure=true
jdbc.testConnectionOnCheckin=true
